name: covid19india
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  connectivity: ^0.4.8+5
  fluttertoast: ^4.0.0
  flutter_staggered_animations: ^0.1.2
  fl_chart: ^0.9.4
  url_launcher: ^5.4.7
  carousel_slider: ^2.0.0
  intro_slider: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
  - images/
  fonts:
  - family: Lato
    fonts:
    - asset: fonts/Lato-Regular.ttf
  

